projet_photo:
    resource: "@ProjetPhotoBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: @AppBundle/Controller/
    type:     annotation
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"