projet_photo:
    resource: "@ProjetPhotoBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: @AppBundle/Controller/
    type:     annotation
os_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"