<?php

namespace Projet\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository
{

    public function isExisting(Personne $personne)
    {
        $p = $this->getExistingPersonne($personne);
        return $p != null;
    }

    public function getExistingPersonne(Personne $personne)
    {
        return $this->findOneBy(array(
            'nom' => $personne->getNom(),
            'prenom' => $personne->getPrenom(),
            'adresse' => $personne->getAdresse()
        ));
    }

}
